---
base.url: http://localhost:8081
environment: ${ENVIRONMENT:local}
service.name: resource-server
server:
  port: 8081

spring:
  main.banner-mode: "off"
  profiles.active: ${PROFILES_ACTIVE:message-debug-logging}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/SpringBootKeycloak




